module.exports = {
	// admin
	authListUrl: '/api/authentication/auth',
	baseUrl: 'http://192.168.199.66:8000',
	loginUrl: '/api/login',
	logoutUrl: '/api/logout',
	userInfoUrl: '/api/authentication/user',
	// article
	authorUrl: '/api/user',
	articleTableDataUrl: '/api/article',
	articleDataCountUrl: '/api/article/count',
	// comment
	commentTableDataUrl: '/api/comment',
	commentDataCountUrl: '/api/comment/count',
	// tag
	tagTableDataUrl: '/api/tag',
	tagDataCountUrl: '/api/tag/count',
	// user
	roleUrl: '/api/role',
	userTableDataUrl: '/api/user',
	userDataCountUrl: '/api/user/count',
	// role
	authMapUrl: '/api/authMap',
	roleMapUrl: '/api/roleMap',
	roleTableDataUrl: '/api/role',
	roleDataCountUrl: '/api/role/count',
	// module
	authUrl: '/api/auth',
	authMapUrl: '/api/authmap',
	moduleTableDataUrl: '/api/module',
	moduleDataCountUrl: '/api/module/count',
	// auth
	authTableDataUrl: '/api/auth',
	authDataCountUrl: '/api/auth/count',
}